version: '3.8'

services:
  # Service de l'API Flask
  web:
    build: .
    ports:
      - "5002:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DB=mydatabase

  # Service de la base de données MariaDB
  db:
    image: mariadb/server:10.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
